;;; package --- Summary
;;; Commentary:
;;; All settings related to fonts/faces
;;; Code:

;; set default font
(add-to-list 'default-frame-alist
             '(font . "Inconsolata-20"))

;; Unicode emoji code ranges
(set-fontset-font t '(#x231a . #x231b) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x23e9 . #x23ec) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x23f0 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x23f3 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x25fd . #x25fe) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x2614 . #x2615) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x2648 . #x2653) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x267f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2693 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26a1 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x26aa . #x26ab) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x26bd . #x26be) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x26c4 . #x26c5) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26ce (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26d4 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26ea (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x26f2 . #x26f3) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26f5 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26fa (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26fd (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2705 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x270a . #x270b) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2728 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x274c (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x274e (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x2753 . #x2755) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2757 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x2795 . #x2797) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x27b0 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x27bf (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x2b1b . #x2b1c) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2b50 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2b55 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f004 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f0cf (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f18e (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f191 . #x1f19a) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f201 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f21a (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f22f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f232 . #x1f236) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f238 . #x1f23a) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f250 . #x1f251) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f300 . #x1f30c) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f30d . #x1f30e) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f30f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f310 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f311 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f312 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f313 . #x1f315) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f316 . #x1f318) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f319 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f31a (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f31b (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f31c (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f31d . #x1f31e) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f31f . #x1f320) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f32d . #x1f32f) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f330 . #x1f331) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f332 . #x1f333) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f334 . #x1f335) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f337 . #x1f34a) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f34b (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f34c . #x1f34f) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f350 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f351 . #x1f37b) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f37c (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f37e . #x1f37f) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f380 . #x1f393) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f3a0 . #x1f3c4) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3c5 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3c6 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3c7 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3c8 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3c9 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3ca (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f3cf . #x1f3d3) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f3e0 . #x1f3e3) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3e4 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f3e5 . #x1f3f0) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3f4 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f3f8 . #x1f407) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f408 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f409 . #x1f40b) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f40c . #x1f40e) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f40f . #x1f410) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f411 . #x1f412) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f413 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f414 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f415 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f416 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f417 . #x1f429) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f42a (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f42b . #x1f43e) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f440 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f442 . #x1f464) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f465 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f466 . #x1f46b) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f46c . #x1f46d) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f46e . #x1f4ac) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f4ad (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f4ae . #x1f4b5) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f4b6 . #x1f4b7) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f4b8 . #x1f4eb) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f4ec . #x1f4ed) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f4ee (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f4ef (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f4f0 . #x1f4f4) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f4f5 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f4f6 . #x1f4f7) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f4f8 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f4f9 . #x1f4fc) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f4ff . #x1f502) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f503 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f504 . #x1f507) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f508 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f509 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f50a . #x1f514) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f515 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f516 . #x1f52b) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f52c . #x1f52d) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f52e . #x1f53d) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f54b . #x1f54e) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f550 . #x1f55b) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f55c . #x1f567) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f57a (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f595 . #x1f596) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5a4 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f5fb . #x1f5ff) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f600 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f601 . #x1f606) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f607 . #x1f608) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f609 . #x1f60d) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f60e (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f60f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f610 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f611 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f612 . #x1f614) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f615 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f616 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f617 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f618 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f619 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f61a (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f61b (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f61c . #x1f61e) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f61f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f620 . #x1f625) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f626 . #x1f627) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f628 . #x1f62b) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f62c (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f62d (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f62e . #x1f62f) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f630 . #x1f633) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f634 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f635 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f636 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f637 . #x1f640) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f641 . #x1f644) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f645 . #x1f64f) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f680 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f681 . #x1f682) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f683 . #x1f685) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f686 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f687 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f688 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f689 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f68a . #x1f68b) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f68c (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f68d (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f68e (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f68f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f690 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f691 . #x1f693) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f694 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f695 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f696 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f697 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f698 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f699 . #x1f69a) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f69b . #x1f6a1) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6a2 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6a3 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f6a4 . #x1f6a5) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6a6 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f6a7 . #x1f6ad) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f6ae . #x1f6b1) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6b2 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f6b3 . #x1f6b5) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6b6 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f6b7 . #x1f6b8) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f6b9 . #x1f6be) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6bf (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6c0 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f6c1 . #x1f6c5) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6cc (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6d0 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f6d1 . #x1f6d2) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6d5 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f6d6 . #x1f6d7) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f6eb . #x1f6ec) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f6f4 . #x1f6f6) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f6f7 . #x1f6f8) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6f9 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6fa (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f6fb . #x1f6fc) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f7e0 . #x1f7eb) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f90c (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f90d . #x1f90f) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f910 . #x1f918) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f919 . #x1f91e) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f91f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f920 . #x1f927) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f928 . #x1f92f) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f930 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f931 . #x1f932) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f933 . #x1f93a) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f93c . #x1f93e) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f93f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f940 . #x1f945) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f947 . #x1f94b) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f94c (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f94d . #x1f94f) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f950 . #x1f95e) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f95f . #x1f96b) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f96c . #x1f970) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f971 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f972 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f973 . #x1f976) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f977 . #x1f978) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f97a (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f97b (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f97c . #x1f97f) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f980 . #x1f984) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f985 . #x1f991) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f992 . #x1f997) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f998 . #x1f9a2) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f9a3 . #x1f9a4) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f9a5 . #x1f9aa) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f9ab . #x1f9ad) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f9ae . #x1f9af) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f9b0 . #x1f9b9) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f9ba . #x1f9bf) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f9c0 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f9c1 . #x1f9c2) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f9c3 . #x1f9ca) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f9cb (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f9cd . #x1f9cf) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f9d0 . #x1f9e6) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1f9e7 . #x1f9ff) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1fa70 . #x1fa73) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1fa74 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1fa78 . #x1fa7a) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1fa80 . #x1fa82) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1fa83 . #x1fa86) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1fa90 . #x1fa95) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1fa96 . #x1faa8) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1fab0 . #x1fab6) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1fac0 . #x1fac2) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t '(#x1fad0 . #x1fad6) (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x00a9 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x00ae (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x203c (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2049 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2122 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2139 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2194 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2195 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2196 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2197 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2198 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2199 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x21a9 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x21aa (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2328 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x23cf (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x23ed (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x23ee (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x23ef (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x23f1 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x23f2 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x23f8 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x23f9 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x23fa (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x24c2 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x25aa (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x25ab (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x25b6 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x25c0 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x25fb (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x25fc (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2600 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2601 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2602 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2603 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2604 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x260e (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2611 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2618 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x261d (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2620 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2622 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2623 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2626 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x262a (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x262e (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x262f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2638 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2639 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x263a (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2640 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2642 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x265f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2660 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2663 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2665 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2666 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2668 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x267b (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x267e (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2692 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2694 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2695 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2696 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2697 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2699 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x269b (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x269c (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26a0 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26a7 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26b0 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26b1 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26c8 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26cf (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26d1 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26d3 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26e9 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26f0 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26f1 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26f4 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26f7 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26f8 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x26f9 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2702 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2708 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2709 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x270c (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x270d (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x270f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2712 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2714 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2716 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x271d (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2721 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2733 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2734 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2744 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2747 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2763 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2764 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x27a1 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2934 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2935 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2b05 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2b06 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x2b07 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x3030 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x303d (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x3297 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x3299 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f170 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f171 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f17e (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f17f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f202 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f237 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f321 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f324 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f325 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f326 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f327 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f328 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f329 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f32a (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f32b (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f32c (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f336 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f37d (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f396 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f397 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f399 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f39a (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f39b (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f39e (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f39f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3cb (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3cc (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3cd (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3ce (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3d4 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3d5 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3d6 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3d7 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3d8 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3d9 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3da (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3db (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3dc (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3dd (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3de (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3df (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3f3 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3f5 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f3f7 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f43f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f441 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f4fd (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f549 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f54a (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f56f (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f570 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f573 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f574 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f575 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f576 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f577 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f578 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f579 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f587 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f58a (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f58b (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f58c (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f58d (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f590 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5a5 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5a8 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5b1 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5b2 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5bc (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5c2 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5c3 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5c4 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5d1 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5d2 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5d3 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5dc (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5dd (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5de (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5e1 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5e3 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5e8 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5ef (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5f3 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f5fa (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6cb (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6cd (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6ce (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6cf (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6e0 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6e1 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6e2 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6e3 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6e4 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6e5 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6e9 (font-spec :size 20 :name "Noto Color Emoji"))
(set-fontset-font t #x1f6f0 (font-spec :size 20 :name "Inconsolata"))
(set-fontset-font t #x1f6f3 (font-spec :size 20 :name "Noto Color Emoji"))

;; Fallback font for special cases
;; (set-fontset-font t nil (font-spec :size 20 :name "DejaVu Sans Mono"))

(provide 'init-fonts)

;;; init-fonts.el ends here
